- id: scaleio-gw
  type: group
  role: [scaleio-gw]
  tasks:
    - hiera
    - globals
    - tools
    - logging
    - netconfig
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: parallel

- id: scaleio-mdm
  type: group
  role: [scaleio-mdm]
  tasks:
    - hiera
    - globals
    - tools
    - logging
    - netconfig
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: parallel

- id: scaleio-tb
  type: group
  role: [scaleio-tb]
  tasks:
    - hiera
    - globals
    - tools
    - logging
    - netconfig
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: parallel
