#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'fuel-plugin-builder==2.0.5.dev','console_scripts','fpb'
__requires__ = 'fuel-plugin-builder==2.0.5.dev'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('fuel-plugin-builder==2.0.5.dev', 'console_scripts', 'fpb')()
    )
